oauth:
  google:
    tokeninfo: https://www.googleapis.com/oauth2/v3/tokeninfo
    userinfo: https://www.googleapis.com/oauth2/v3/userinfo

spring:
  datasource:
    url: jdbc:sqlite:class_c.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none

domain:
  defaults:
    user:
      gradSession:
        semester: SPRING
      major: Computer Science